### Create new TEST

POST http://localhost:5003/api/tests
Content-Type: application/json
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjJmOGQxNjk4OTcyNTc4ZTQ0YWViMjIiLCJpYXQiOjE3MTQ5NDU0NjcsImV4cCI6MTcxNjY3MzQ2N30.a2hs087K6khQN6bSZT-NVVqpju25CeKqszsmO0UfaqM"

{
    "question":"How many children are there in computer room?",
    "category":"7-14",
    "correctAnswer":"5",
    "first":"4",
    "second":"3",
    "third":"2"
}


### Bulk Insert

POST http://localhost:5003/api/tests/bulk-insert
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1OWY5NWE0NjI5ZDZhZDFhOGQ3MjYiLCJpYXQiOjE3MDk1NDc0MTUsImV4cCI6MTcxMTI3NTQxNX0.CAeSg6MKCPlrnrbCuYPJ4akdnPxKcvqIHxLDtYVJGFc

{
  "courses": [
    { "courseName": "",     
     "category": "",
     "correctAnswer":"",
     "first":"",
     "second":"",
     "third":"" },
    { "courseName": "",
         "category": "",
         "correctAnswer":"",
         "first":"",
         "second":"",
         "third":"" },
    { "courseName": "Confections",    "category": "Desserts, candies, and sweet breads","correctAnswer":"","first":"","second":"","third":"" },
    { "courseName": "Dairy Products", "category": "Cheeses","correctAnswer":"","first":"","second":"","third":"" },
    { "courseName": "Grains/Cereals", "category": "Breads, crackers, pasta, and cereal","correctAnswer":"","first":"","second":"","third":"" },
    { "courseName": "Meat/Poultry",   "category": "Prepared meats","correctAnswer":"","first":"","second":"","third":"" },
    { "courseName": "Produce",        "category": "Dried fruit and bean curd","correctAnswer":"","first":"","second":"","third":"" },
    { "courseName": "Seafood",        "category": "Seaweed and fish","correctAnswer":"","first":"","second":"","third":"" }
  ]
}


### GET TEST By Id
GET http://localhost:5003/tests/65ce1d2877c9c036cefce4d6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRmMGM3MzI4YTliM2U2YjNlMTg0NzkiLCJpYXQiOjE3MDkxMjA5MDV9.DyftnbwYqeY_wDAoq8FY6b2-rJj1hQVIlwD-CqSHAwA


### GET All TESTS
GET http://localhost:5001/api/tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1YmRlMTUzODkxMzUxMDFiZTA1YjgiLCJpYXQiOjE3MTAxNjMyNDAsImV4cCI6MTcxMTg5MTI0MH0.jM-YYuBsufBb1QwS1RakAhGu2lizf8F-inyqfKVwDmM

### DELETE Test By Id
DELETE http://localhost:5003/tests/65ce1d2877c9c036cefce4d6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWRmMGM3MzI4YTliM2U2YjNlMTg0NzkiLCJpYXQiOjE3MDkxMjA5MDV9.DyftnbwYqeY_wDAoq8FY6b2-rJj1hQVIlwD-CqSHAwA

### Update Test By Id
PATCH http://localhost:5003/tests/65ce1d2877c9c036cefce4d6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1YmRlMTUzODkxMzUxMDFiZTA1YjgiLCJpYXQiOjE3MTAxNjMyNDAsImV4cCI6MTcxMTg5MTI0MH0.jM-YYuBsufBb1QwS1RakAhGu2lizf8F-inyqfKVwDmM

{
   "courseName": "Bevqerages", "category": "Soft, Tea" 
}
