### Create New User
POST https://localhost:5003/api/auth/register
Content-Type: application/json
 
{ 
    "username": "something", 
    "password": "Pro247!!" ,
    "firstname":"murat",
    "lastname":"vuranok",
    "email":"some@hotmail.com"
}
 

### Login

POST https://localhost:5003/api/auth/login
Content-Type: application/json
 
{ 
    "username": "natavan", 
    "password": "Pro247!!" 
}  